### ISSUE TITLE
Error after executing "brew install mopidy"

### ISSUE THREAD

**Issue by jtakyiyeboah** [mopidy/homebrew-mopidy#18] opened 2017-12-10 04:08 UTC
```
 python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel
Last 15 lines from /Users/JeffreyTakyi-Yeboah/Library/Logs/Homebrew/python-pykka/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/python-pykka/1.2.1
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools
```

It also says that mopidy is not installed

**Comment by XintongHao** [comment] 2018-03-10 23:08
same issue

**Comment by jodal** [comment] 2018-06-03 23:37
Looks like an issue with your system's Python installation or `PYTHONPATH`. Since this isn't caused by this tap itself and the issue is quite old, I'm closing it.

**Closed as completed by jodal** 2018-06-03 23:37 UTC
